command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "$DATABRICKS_APP_PORT"

env:
  - name: LAKEBASE_ENDPOINT
    valueFrom: postgres

resources:
  - name: lakebase-ticketingsystem
    lakebase:
      postgres:
        project: ticketingsystem
        branch: production
        database: databricks_postgres